// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tpmlsmDigest struct {
	_ structs.HostLayout
	B [32]uint8
}

type tpmlsmEvent struct {
	_       structs.HostLayout
	Pid     uint32
	Dev     uint32
	Comm    [16]uint8
	Allowed uint8
	_       [3]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tpmlsmMapAllowedHashes = "allowed_hashes"
	tpmlsmMapEvents        = "events"
	tpmlsmMapTaskOk        = "task_ok"
	tpmlsmMapTpmDevs       = "tpm_devs"
	tpmlsmProgOnExec       = "on_exec"
	tpmlsmProgOnFork       = "on_fork"
	tpmlsmProgTpmOpen      = "tpm_open"
	tpmlsmVarUnused        = "unused"
)

// loadTpmlsm returns the embedded CollectionSpec for tpmlsm.
func loadTpmlsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TpmlsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tpmlsm: %w", err)
	}

	return spec, err
}

// loadTpmlsmObjects loads tpmlsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tpmlsmObjects
//	*tpmlsmPrograms
//	*tpmlsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTpmlsmObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTpmlsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tpmlsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tpmlsmSpecs struct {
	tpmlsmProgramSpecs
	tpmlsmMapSpecs
	tpmlsmVariableSpecs
}

// tpmlsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tpmlsmProgramSpecs struct {
	OnExec  *ebpf.ProgramSpec `ebpf:"on_exec"`
	OnFork  *ebpf.ProgramSpec `ebpf:"on_fork"`
	TpmOpen *ebpf.ProgramSpec `ebpf:"tpm_open"`
}

// tpmlsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tpmlsmMapSpecs struct {
	AllowedHashes *ebpf.MapSpec `ebpf:"allowed_hashes"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	TaskOk        *ebpf.MapSpec `ebpf:"task_ok"`
	TpmDevs       *ebpf.MapSpec `ebpf:"tpm_devs"`
}

// tpmlsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tpmlsmVariableSpecs struct {
	Unused *ebpf.VariableSpec `ebpf:"unused"`
}

// tpmlsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTpmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type tpmlsmObjects struct {
	tpmlsmPrograms
	tpmlsmMaps
	tpmlsmVariables
}

func (o *tpmlsmObjects) Close() error {
	return _TpmlsmClose(
		&o.tpmlsmPrograms,
		&o.tpmlsmMaps,
	)
}

// tpmlsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTpmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type tpmlsmMaps struct {
	AllowedHashes *ebpf.Map `ebpf:"allowed_hashes"`
	Events        *ebpf.Map `ebpf:"events"`
	TaskOk        *ebpf.Map `ebpf:"task_ok"`
	TpmDevs       *ebpf.Map `ebpf:"tpm_devs"`
}

func (m *tpmlsmMaps) Close() error {
	return _TpmlsmClose(
		m.AllowedHashes,
		m.Events,
		m.TaskOk,
		m.TpmDevs,
	)
}

// tpmlsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTpmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type tpmlsmVariables struct {
	Unused *ebpf.Variable `ebpf:"unused"`
}

// tpmlsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTpmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type tpmlsmPrograms struct {
	OnExec  *ebpf.Program `ebpf:"on_exec"`
	OnFork  *ebpf.Program `ebpf:"on_fork"`
	TpmOpen *ebpf.Program `ebpf:"tpm_open"`
}

func (p *tpmlsmPrograms) Close() error {
	return _TpmlsmClose(
		p.OnExec,
		p.OnFork,
		p.TpmOpen,
	)
}

func _TpmlsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tpmlsm_bpfel.o
var _TpmlsmBytes []byte
